name: Actualizar avisos

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descargar JSON desde Google Apps Script
        run: |
          curl -fL "https://script.google.com/macros/s/AKfycbykLfJ-t4N3i6In5g8QytlIYNxG7-1pjLHvrVYl8qb9iaODiKTb3pX9g4O6iuzQ5618kw/exec" -o avisos_nuevo.json

      - name: Validar JSON
        run: |
          python -m json.tool avisos_nuevo.json > /dev/null

      - name: Comparar y actualizar
        run: |
          if cmp -s "demo/regazziharina/avisos.json" "avisos_nuevo.json"; then
            echo "El archivo no cambió."
            rm avisos_nuevo.json
          else
            echo "El archivo cambió."
            mv avisos_nuevo.json "demo/regazziharina/avisos.json"

            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add "demo/regazziharina/avisos.json"
            git commit -m "Actualizar avisos"
            git push
          fi
